name: wf-shrd-docker

# https://docs.docker.com/build/ci/github-actions/

on:
  workflow_call:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: false
        default: true
      platforms: 
        description: 'build platforms (amd64, arm64, etc)'
        type: string
        required: false
        default: 'linux/amd64,linux/arm64'
      dockerfile:
        description: 'Dockerfile name'
        type: string
        required: false
        default: 'Dockerfile'
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ inputs.dry_run == false && github.repository || format('{0}/{1}', vars.DOCKERHUB_USERNAME, 'test') }}

jobs:
  job-build-and-push:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=dry-run,enable=${{ inputs.dry_run }}
            type=raw,value=latest,enable=${{ !inputs.dry_run }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          #linux/amd64,linux/386
          #linux/arm64,linux/arm/v7,linux/arm/v6
          #linux/riscv64
          #linux/ppc64le
          #linux/s390x
          platforms: ${{ inputs.platforms }}
          file: ${{ inputs.dockerfile }}
          context: .
          sbom: true
          push: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker Hub Description
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ env.IMAGE_NAME }}
          provider: dockerhub
          # use github repo description (limit: max 100 chars)
          short_description: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }}
          readme_file: 'README.md'

# END #
